// ---------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY BEHAVIAC DESIGNER, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// ---------------------------------------------------------------------

#ifndef _BEHAVIAC_MEMBER_VISITOR_H_
#define _BEHAVIAC_MEMBER_VISITOR_H_

#include "behaviac_agent_headers.h"

// Agent property and method handlers


struct METHOD_TYPE_FirstAgent_HelloWorld { };
template<> inline void FirstAgent::_Execute_Method_<METHOD_TYPE_FirstAgent_HelloWorld>(behaviac::string p0)
{
	this->FirstAgent::HelloWorld(p0);
}


#endif // _BEHAVIAC_MEMBER_VISITOR_H_
