%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(player_1_pb).
-define(player_1_pb, true).

-define(player_1_pb_gpb_version, "4.13.0").

-ifndef('PLAYER_C_ACCOUNT_LOGIN_PB_H').
-define('PLAYER_C_ACCOUNT_LOGIN_PB_H', true).
-record(player_c_account_login,
        {account = <<>>         :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('PLAYER_P_ROLE_INFO_PB_H').
-define('PLAYER_P_ROLE_INFO_PB_H', true).
-record(player_p_role_info,
        {id = 0                 :: non_neg_integer() | undefined, % = 1, 32 bits
         name = <<>>            :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('PLAYER_S_ACCOUNT_LOGIN_PB_H').
-define('PLAYER_S_ACCOUNT_LOGIN_PB_H', true).
-record(player_s_account_login,
        {role_list = []         :: [player_1_pb:player_p_role_info()] | undefined % = 1
        }).
-endif.

-ifndef('PLAYER_C_SELECT_ROLE_PB_H').
-define('PLAYER_C_SELECT_ROLE_PB_H', true).
-record(player_c_select_role,
        {id = 0                 :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PLAYER_S_SELECT_ROLE_PB_H').
-define('PLAYER_S_SELECT_ROLE_PB_H', true).
-record(player_s_select_role,
        {id = 0                 :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-ifndef('PLAYER_C_CREATE_ROLE_PB_H').
-define('PLAYER_C_CREATE_ROLE_PB_H', true).
-record(player_c_create_role,
        {name = <<>>            :: iodata() | undefined % = 1
        }).
-endif.

-ifndef('PLAYER_S_CREATE_ROLE_PB_H').
-define('PLAYER_S_CREATE_ROLE_PB_H', true).
-record(player_s_create_role,
        {role_list = []         :: [player_1_pb:player_p_role_info()] | undefined % = 1
        }).
-endif.

-endif.
