%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(test_0_pb).
-define(test_0_pb, true).

-define(test_0_pb_gpb_version, "4.13.0").

-ifndef('PROTO_TEST_PB_H').
-define('PROTO_TEST_PB_H', true).
-record(proto_test,
        {str = <<>>             :: iodata() | undefined, % = 1
         ui32 = 0               :: non_neg_integer() | undefined, % = 2, 32 bits
         rp_str = []            :: [iodata()] | undefined, % = 3
         rp_ui32 = []           :: [non_neg_integer()] | undefined % = 4, 32 bits
        }).
-endif.

-ifndef('PROTO_TEST2_PB_H').
-define('PROTO_TEST2_PB_H', true).
-record(proto_test2,
        {str = <<>>             :: iodata() | undefined, % = 1
         ti = undefined         :: test_0_pb:test_import() | undefined % = 2
        }).
-endif.

-ifndef('PROTO_TEST3_PB_H').
-define('PROTO_TEST3_PB_H', true).
-record(proto_test3,
        {str = <<>>             :: iodata() | undefined, % = 1
         ti = undefined         :: test_0_pb:test_import() | undefined % = 2
        }).
-endif.

-ifndef('PROTO_TEST4_PB_H').
-define('PROTO_TEST4_PB_H', true).
-record(proto_test4,
        {t3 = undefined         :: test_0_pb:proto_test3() | undefined, % = 1
         ti = undefined         :: test_0_pb:test_import() | undefined % = 2
        }).
-endif.

-ifndef('TEST_IMPORT_PB_H').
-define('TEST_IMPORT_PB_H', true).
-record(test_import,
        {ui32 = 0               :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
