%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(test_i_pb).
-define(test_i_pb, true).

-define(test_i_pb_gpb_version, "4.13.0").

-ifndef('TEST_IMPORT_PB_H').
-define('TEST_IMPORT_PB_H', true).
-record(test_import,
        {ui32 = 0               :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
